export { default as Home } from './Home';
export { default as Preloader } from './Preloader';
export { default as Nav } from './Nav';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as PokemonDetail } from './PokemonDetail';
export { default as NotFound } from './404';
export { default as ProtectedRoute } from './ProtectedRoute';
export { default as GlobalLoading } from './GlobalLoading';
export { Favourites } from './Favourites';
export { default as Notes } from './Notes';
export { default as Modal } from './Modal';
export { default as FavouriteDetail } from './Favourites/FavouriteDetail';
